apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kaaval.controlPlane.fullname" . }}-secrets
  labels:
{{ include "kaaval.controlPlane.labels" . | indent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.secrets.adminPassword | b64enc | quote }}
  secret-key: {{ .Values.secrets.secretKey | b64enc | quote }}
  refresh-secret-key: {{ .Values.secrets.refreshSecretKey | b64enc | quote }}
  database-url: {{ printf "postgresql://%s:%s@%s-postgresql:%s/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "kaaval.fullname" .) "5432" .Values.postgresql.auth.database | b64enc | quote }}
