{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kaaval.controlPlane.fullname" . }}
  labels:
{{ include "kaaval.controlPlane.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kaaval.controlPlane.fullname" . }}
  labels:
{{ include "kaaval.controlPlane.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kaaval.controlPlane.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kaaval.controlPlane.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
